#ifndef CONSTANTS_H
#define CONSTANTS_H

#define MAX_PORT_STR_LEN 7
#define DECIMAL_INTEGER_BASE 10
#define PORT_NUMBER_DEFAULT 8000
#define BACKLOG_DEFAULT 10
#define BUFFER_SIZE 1024
#define MAX_NAME_LEN 32
#define MAX_ANNOUNCE_TEXT_LEN 64
#define MAX_CONNECTIONS 100

#endif // !CONSTANTS_H
