#ifndef CONSTANTS_H
#define CONSTANTS_H

#define MAX_PORT_STR_LEN 7
#define DECIMAL_INTEGER_BASE 10
#define PORT_NUMBER_DEFAULT 8000
#define BACKLOG_DEAULT 10
#define BUFFER_SIZE 1024
#define BRODCAST_MESSAGE_LENGTH 30
#define MAX_CONNECTIONS 100

#endif // !CONSTANTS_H
